export const data_test_reports =()=>{
    let obj_data=[
        {
            date_upload:'19/08/2023',
            purchase_orders:'#PO-1234, #PO-1289',
            status_error:"Pending of Corrections by Vendor",
            transaction_statement:'Seller has complied with each applicable subsection of FDCA Sec. 581(27)(A)-(G).',
            sender_name:'AmerisourceBergen',
            sender_SGLN:'9006477000001',
            sender_location_name:'AmerisourceBergen TX',
            sender_location_address:'Ladera del Cubilete 211, col. La Ladera',
            receiver_location_name:'Healix LLC',
            receiver_location_address:'Healix Houston, TX address',
            shipment_date:'19/08/2023',
            
            transactions_po:[
                {
                    purchase_order:'12487',
                    quantity:20,
                    items_info:[
                        {
                            sgtin:'145278956324',
                            ndc:'14789635',
                            quantity_item:'3',
                            product_name:'PEMETREXED DISODIUM (ALIMTA) 500MG SDV 1VL',
                            dosage:'PILL',
                            strength:'100mg',
                            container_size:"500 pills",
                            lot_number:'LOT1MAG',
                            level_1:'urn:epc:id:sgtin:0355154.394495.40072894693743',
                            level_2:'urn:epc:id:sgtin:0355154.094497.40095247428190',
                            level_3:'urn:epc:id:sgtin:0355154.094497.40095247428191',
                            transaction_history:[
                                {
                                    shipment_date:'fechita',
                                    purchase_orders_th:'PO-180',
                                    sender_name:'Octapharma',
                                    sender_SGLN:'172826864.5789347545.956897',
                                    sender_street_addr1:'Ladera del Cubilete',
                                    sender_street_addr2:'Room 211',
                                    sender_city:'Querétaro',
                                    sender_state:'Qro',
                                    sender_postalCode:"76148",
                                    sender_countryCode:'MX',
                                    sender_loc_name:'Octapharma',
                                    sender_loc_street_addr1:'Ladera del Cubilete',
                                    sender_loc_street_addr2:'Room 211',
                                    sender_loc_city:'Querétaro',
                                    sender_loc_state:'Qro',
                                    sender_loc_postalCode:"76148",
                                    sender_loc_countryCode:'MX',

                                    receiver_name:'Octapharma',
                                    receiver_SGLN:'',
                                    receiver_street_addr1:'Ladera del Cubilete',
                                    receiver_street_addr2:'Room 211',
                                    receiver_city:'Querétaro',
                                    receiver_state:'Qro',
                                    receiver_postalCode:"76148",
                                    receiver_countryCode:'MX',
                                    receiver_loc_name:'Octapharma',
                                    receiver_loc_street_addr1:'Ladera del Cubilete',
                                    receiver_loc_street_addr2:'Room 211',
                                    receiver_loc_city:'Querétaro',
                                    receiver_loc_state:'Qro',
                                    receiver_loc_postalCode:"76148",
                                    receiver_loc_countryCode:'MX',
                                },
                                {
                                    shipment_date:'fechita',
                                    purchase_orders_th:'PO-450',
                                    sender_name:'Octapharma',
                                    sender_SGLN:'172826864.5789347545.956897',
                                    sender_street_addr1:'Ladera del Cubilete',
                                    sender_street_addr2:'Room 211',
                                    sender_city:'Querétaro',
                                    sender_state:'Qro',
                                    sender_postalCode:"76148",
                                    sender_countryCode:'MX',
                                    sender_loc_name:'Octapharma',
                                    sender_loc_street_addr1:'Ladera del Cubilete',
                                    sender_loc_street_addr2:'Room 211',
                                    sender_loc_city:'Querétaro',
                                    sender_loc_state:'Qro',
                                    sender_loc_postalCode:"76148",
                                    sender_loc_countryCode:'MX',

                                    receiver_name:'Octapharma',
                                    receiver_SGLN:'',
                                    receiver_street_addr1:'Ladera del Cubilete',
                                    receiver_street_addr2:'Room 211',
                                    receiver_city:'Querétaro',
                                    receiver_state:'Qro',
                                    receiver_postalCode:"76148",
                                    receiver_countryCode:'MX',
                                    receiver_loc_name:'Octapharma',
                                    receiver_loc_street_addr1:'Ladera del Cubilete',
                                    receiver_loc_street_addr2:'Room 211',
                                    receiver_loc_city:'Querétaro',
                                    receiver_loc_state:'Qro',
                                    receiver_loc_postalCode:"76148",
                                    receiver_loc_countryCode:'MX',
                                },
                                {
                                    shipment_date:'fechita',
                                    purchase_orders_th:'PO-000',
                                    sender_name:'Octapharma',
                                    sender_SGLN:'172826864.5789347545.956897',
                                    sender_street_addr1:'Ladera del Cubilete',
                                    sender_street_addr2:'Room 211',
                                    sender_city:'Querétaro',
                                    sender_state:'Qro',
                                    sender_postalCode:"76148",
                                    sender_countryCode:'MX',
                                    sender_loc_name:'Octapharma',
                                    sender_loc_street_addr1:'Ladera del Cubilete',
                                    sender_loc_street_addr2:'Room 211',
                                    sender_loc_city:'Querétaro',
                                    sender_loc_state:'Qro',
                                    sender_loc_postalCode:"76148",
                                    sender_loc_countryCode:'MX',

                                    receiver_name:'Octapharma',
                                    receiver_SGLN:'',
                                    receiver_street_addr1:'Ladera del Cubilete',
                                    receiver_street_addr2:'Room 211',
                                    receiver_city:'Querétaro',
                                    receiver_state:'Qro',
                                    receiver_postalCode:"76148",
                                    receiver_countryCode:'MX',
                                    receiver_loc_name:'Octapharma',
                                    receiver_loc_street_addr1:'Ladera del Cubilete',
                                    receiver_loc_street_addr2:'Room 211',
                                    receiver_loc_city:'Querétaro',
                                    receiver_loc_state:'Qro',
                                    receiver_loc_postalCode:"76148",
                                    receiver_loc_countryCode:'MX',
                                }
                            ],
                            item_internal_movements:[
                                
                                    {
                                        id: "2886",
                                        tranid: "IA-000006",
                                        tranid_createdfrom: "",
                                        subsidiary: "Healix LLC : Complete Infusion Solutions",
                                        subsidiary_id: "4",
                                        item: "00143998303",
                                        item_id: "10008",
                                        quantity: "90",
                                        trandate: "6/6/2023",
                                        inventorynumber_inventorydetail: "489300309",
                                        inventorynumber_inventorydetail_id: "57",
                                        quantity_inventorydetail: "90",
                                        recordtype: "inventoryadjustment",
                                        entity: "Fake Vendor name",
                                        location: "A004",
                                        location_id: "640",
                                        formulatext: "6014 Penn Ave.  , Pittsburgh  US",
                                        displayname_item: "CEFAZOLIN SODIUM 10GM MDV 10/PK**",
                                        unit: "Vial",
                                        address_vendor: "fake address 211",
                                        custbody_atlas_inv_adj_reason: "Fake reason text of an inventory adjustment",
                                        custbody_tkio_ship_to_acc_number_purchaseorder: "678787878"
                                    },
                                
                            ]

                        }
                    ]
                    
                },
                
            ]
        },
        
    ];
    return obj_data;
}